package cli

import (
	"fmt"
	"time"

	"github.com/spf13/cobra"
)

var (
	logsFollow bool
	logsTail   int
)

var logsCmd = &cobra.Command{
	Use:   "logs <job-id>",
	Short: "View logs for a job",
	Long:  `View logs generated by an asynchronous job.`,
	Args:  cobra.ExactArgs(1),
	RunE:  runLogs,
}

func init() {
	logsCmd.Flags().BoolVarP(&logsFollow, "follow", "f", false, "Follow log output")
	logsCmd.Flags().IntVarP(&logsTail, "tail", "n", 0, "Number of lines to show from the end (0 = all)")
}

func runLogs(cmd *cobra.Command, args []string) error {
	jobID := args[0]

	if applyJobQueue == nil {
		return fmt.Errorf("job queue not initialized")
	}

	job, err := applyJobQueue.Get(jobID)
	if err != nil {
		return err
	}

	if !logsFollow {
		// Show logs once
		start := 0
		if logsTail > 0 && len(job.Logs) > logsTail {
			start = len(job.Logs) - logsTail
		}

		for _, log := range job.Logs[start:] {
			fmt.Printf("[%s] [%s] %s: %s\n",
				log.Timestamp.Format("15:04:05"),
				log.Level,
				log.Component,
				log.Message,
			)
		}
		return nil
	}

	// Follow mode: keep showing new logs
	lastLogCount := 0
	for {
		job, err := applyJobQueue.Get(jobID)
		if err != nil {
			return err
		}

		// Print new logs
		if len(job.Logs) > lastLogCount {
			for _, log := range job.Logs[lastLogCount:] {
				fmt.Printf("[%s] [%s] %s: %s\n",
					log.Timestamp.Format("15:04:05"),
					log.Level,
					log.Component,
					log.Message,
				)
			}
			lastLogCount = len(job.Logs)
		}

		// Stop following if job is done
		if job.Status == "completed" || job.Status == "failed" || job.Status == "cancelled" {
			fmt.Printf("\nJob %s (status: %s)\n", jobID, job.Status)
			break
		}

		time.Sleep(500 * time.Millisecond)
	}

	return nil
}
